In [1]:
# Numpy - Numerical Python

In [2]:
num =int(input("Enter a number:-"))
factorial = 1
for i in range (1, num +1):
  factorial = factorial * i

print("The factorial of no is", factorial)


Enter a number:-6
The factorial of no is 720


In [3]:
# numpy

In [4]:
!pip install numpy

In [5]:
import numpy as np

In [6]:
a = [1,2,3,4,5,6]

In [7]:
b = np.array(a)

In [8]:
type(a)

list

In [9]:
type(b)

numpy.ndarray

In [10]:
print (b)

[1 2 3 4 5 6]


In [11]:
b

array([1, 2, 3, 4, 5, 6])

In [12]:
c= np.array([[1,2,3],[4,5,6]])

In [13]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
d = np.array([[[1,2],[3,4]],
              [[4,5],[6,7]]])

In [16]:
d

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [17]:
# attributed

In [18]:
b.ndim

1

In [19]:
c.ndim

2

In [21]:
d.ndim

3

In [22]:
d.shape

(2, 2, 2)

In [23]:
c.shape

(2, 3)

In [24]:
c.size

6

In [25]:
c.dtype

dtype('int64')

In [26]:
# int whole no- int8, int16, int32, int64
# positive int - unsigned int - np. uint16,32
# float - decimal - folat 16,32,64
# bool - True/False - np. bool-
# string - np.str_  ex - "thsuar"
# object - np.object_ ex - "Admin@123"


In [27]:
# method - methodname()

In [29]:
np.random.rand() #- 0 to 1 -

0.727426289506435

In [30]:
np.random.rand(5)

array([0.5211883 , 0.05096729, 0.41633533, 0.8725091 , 0.18723404])

In [31]:
np.random.rand(2,3)

array([[0.53139004, 0.77857102, 0.00759882],
       [0.1082511 , 0.83646438, 0.37123493]])

In [32]:
np.random.randn(5)

array([-0.38754841, -1.04079628, -0.16977694,  0.80261394,  0.29052723])

In [40]:
np.random.randint(1,7)

2

In [41]:
np.mean(c)

np.float64(3.5)

In [42]:
np.max(c)

np.int64(6)

In [43]:
np.min(c)

np.int64(1)

In [44]:
np.std(c)

np.float64(1.707825127659933)

In [45]:
np.var(c)

np.float64(2.9166666666666665)

In [46]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# pandas - panel data
- built on numpy library
- deals with Series and DataFrame


In [48]:
import numpy as np
import pandas as pd

In [49]:
!pip install pandas

In [50]:
num =[45,84,56,95,32,45,12,56]

In [51]:
pd.Series(num)

0    45
1    84
2    56
3    95
4    32
5    45
6    12
7    56
dtype: int64

In [52]:
index_name = ["row1","row2","row3","row4"]

In [55]:
pd.Series(num,index=index_name,name ="Column1")

ValueError: Length of values (8) does not match length of index (4)

In [56]:
data ={"name":["pradip","gayatri","pratiksha"],
       "Age":[18,10,5],
       "City":["Dubai","America","Amzon"]}

In [57]:
pd.Series(data, index=

r1    NaN
r2    NaN
r3    NaN
dtype: object

In [58]:
pd.DataFrame(data, index=[r1','r2','r3]')

name  Age     City
0     pradip   18    Dubai
1    gayatri   10  America
2  pratiksha    5    Amzon