In [1]:
import numpy as np

In [2]:
# Create a 1D array

In [3]:
arr1 = np.array([1,2,3,4,5])

In [4]:
print("1D Array:",arr1)

1D Array: [1 2 3 4 5]


In [5]:
# Create a ZD array

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [7]:
print("2D Array:",arr2)

2D Array: [[1 2 3]
 [4 5 6]]


In [8]:
zeros = np.zeros((2,3))

In [9]:
ones =np.ones((3,3))

In [10]:
randoms = np.random.rand(2,2)

In [11]:
print("Zeros:",zeros)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print("Ones:",ones)

Ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
print("Random:",randoms)

Random: [[0.95921969 0.67997149]
 [0.38583344 0.06625968]]


In [14]:
a = np.array([10,20,30])
b = np.array([1,2,3])

In [15]:
print("Addition:",a+b)

Addition: [11 22 33]


In [17]:
print("Subtraction:", a-b)
print("Multiplication:",a*b)
print("Divison:",a/b)

Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Divison: [10. 10. 10.]


In [18]:
arr = np.array([[1,2,3],[4,5,6]])

In [21]:
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data type:",arr.dtype)

Shape: (2, 3)
Size: 6
Data type: int64


In [22]:
arr = np.array([10,20,30,40,50])

In [23]:
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Sum: 150


In [24]:
arr = np.array ([10,20,30,40,50])

In [25]:
print("First element:",arr[0])
print("Last elment:",arr[-1])
print("Slice [1:4]:",arr[1:4])

First element: 10
Last elment: 50
Slice [1:4]: [20 30 40]
